### ISSUE TITLE
auto-ebs - ERROR - An error occurred when connecting to EC2

### ISSUE THREAD

**Issue by 8vius** [skymill/automated-ebs-snapshots#14]
When I try to use the script for anything I get the error in the title. Is there any way I can debug this issue further to pinpoint what the problem is?

**Comment by sebdah** [comment]
Yeah, that's a pretty lousy message.. 

I would assume that that means that you didn't provide credentials on the command line nor via the environment variables. Try explicitly setting the access and secret key on the command line for debugging this.

**Comment by 8vius** [comment]
I tried directly setting the keys, I have them set as env variables as well and I also tried passing them in in a config file, nothing worked, same error.

**Comment by sebdah** [comment]
I have created a new version of `automated-ebs-snapshots` that hopefully will give some more insights. Try installing it with `pip install -U automated-ebs-snapshots==0.4.1a1`.

**Comment by 8vius** [comment]
`$ automated-ebs-snapshots --config auto-ebs-snapshots.conf --list`
`auto-ebs - INFO - Connecting to AWS EC2 in us-west-2a`
`auto-ebs - ERROR - An error occurred when connecting to EC2`

**Comment by 8vius** [comment]
Maybe I'm missing some configuration in my AWS account?

**Comment by remy** [comment]
Ping. Same issue here too. I also upgraded to 0.4.1a1 - any progress on debugging this?

**Comment by remy** [comment]
Ah, fixed it. It turned out my region doesn't need the letter at the end. I had `us-east-1a`, but changing it to `us-east-1` fixed it.

**Comment by sebdah** [comment]
@remy yeah, if you add an `a` in the end your specifying the AZ, not the region.
