### ISSUE TITLE
List of needed AWS permissions 

### ISSUE THREAD

**Issue by khelll** [skymill/automated-ebs-snapshots#15]
Is there a list of the AWS permissions needed by the tool?

CreateSnapshot
CopySnapshot
DeleteSnapshot
DescribeSnapshots
DescribeSnapshotAttribute
ModifySnapshotAttribute
ResetSnapshotAttribute

**Comment by yumminhuang** [comment]
This is IAM policy that I use. It works well so far.
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "ec2:CreateSnapshot",
        "ec2:CreateTags",
        "ec2:DeleteSnapshot",
        "ec2:DeleteTags",
        "ec2:DescribeAvailabilityZones",
        "ec2:DescribeSnapshots",
        "ec2:DescribeTags",
        "ec2:DescribeVolumeAttribute",
        "ec2:DescribeVolumeStatus",
        "ec2:DescribeVolumes"
      ],
      "Resource": "*"
    }
  ]
}
```

**Comment by sebdah** [comment]
No, there is not yet an widely tested IAM policy, but the one @yumminhuang submitted seems good. I'm gonna add it to the README.

Thanks for the contribution @yumminhuang.
