### ISSUE TITLE
Cannot Use Tool after pip Install 

### ISSUE THREAD

**Issue by onlydole** [skymill/automated-ebs-snapshots#17]
The pip install doesn't allow proper linkage for use in the command line:

`automated-ebs-snapshots: command not found`

**Comment by sebdah** [comment]
Hmm, strage. I cannot reproduce it here. Can you find it on your computer and ensure that the folder is in

**Comment by onlydole** [comment]
What folder do I need to add?

**Comment by sebdah** [comment]
It all depends on the OS and Python settings. But you need to find `automated-ebs-snapshots ` like so:

    find / -name automated-ebs-snapshots

Then add that folder to the `PATH`.

**Comment by onlydole** [comment]
I am unable to add this for some reason, can you put in a bin add step for a later build?
